pneumonia_detection/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pneumonia_home.urls', 'pneumonia_home'), namespace='pneumonia_home')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pneumonia_home/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('/<str:home>', views.index, name='index'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pneumonia_home/models.py
from django.db import models

# Create your models here.

pneumonia_home/views.py
from django.shortcuts import render
from django.http import HttpResponse
import imageio
from PIL import Image
from . import MLmodel, model_covid


def index(request, home=None):
    if home :
        context = {}
        if request.method == 'POST':
            if request.FILES['images']:
                image = imageio.imread(request.FILES.get('images'))
                inp = Image.open(request.FILES.get('images'))
                result_pneumonia = MLmodel.model_call(inp)
                result_covid = model_covid.model_call(inp)
                # print(result_covid, 'result_covid')
                context['result'] = result_pneumonia
                if result_pneumonia == 'Positive':
                    context['result'] = 'Pneumonia Positive'
                    context['image_url'] = '../static/PNEUMONIA_RESULT.jpg'
                else:
                    if result_covid > 0.5:
                        context['result'] = 'Covid Positive'
                        context['image_url'] = '../static/covid_result.jpeg'
                    else:
                        context['result'] = 'Normal'
                        context['image_url'] = '../static/Normal_result_GIF.gif'
                # print(result_pneumonia)
                # print(inp)
                print("Yes It had files")
            print(request.POST)
        return render(request, 'main.html', context)
    else:
        return render(request, 'index1.html')

# Create your views here.

pneumonia_home/templates/index1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Day Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Day
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/day-multipurpose-html-template-for-free/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope-fill"></i><a href="mailto:contact@example.com">MediDoorhelpline@medidoor.med</a>
        <i class="bi bi-phone-fill phone-icon"></i> +91 9238 55488 65
      </div>
      <!-- <div class="social-links d-none d-md-block">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div> -->
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">
      <div class="d-flex align-middle">
        <img src="../static/MediDoor.jpg" alt="MediDoor Logo"> &nbsp;
        <h1 class="logo"><a href="index.html">MediDoor</a></h1>
      </div>
      
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <!-- <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="#pricing">Pricing</a></li>
          <li><a class="nav-link scrollto" href="#team">Team</a></li>
          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>.navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="500">
      <h1>Welcome to MediDoor</h1>
      <h2>We are Group 172 of thriving developers presents MediDoor</h2>
      <a href="{% url 'pneumonia_home:index' 'true' %}" class="btn-get-started scrollto">Get Started</a>
    </div>
  </section><!-- End Hero -->

  


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <!-- {% static '' %} -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

pneumonia_home/templates/time.html
<!DOCTYPE html>
<html>

    <head>
        <title>Image Falling Animation</title>
        <style>
            #container {
                position: relative;
                width: 500px;
                height: 500px;
                background-color: #ddd;
            }

            #image {
                position: absolute;
                top: -100px;
                left: 50%;
                transform: translateX(-50%);
            }

        </style>
    </head>

    <body>
        <div id="container">
            <img id="image" src="../static/bear.jpg" alt="Falling Image">
        </div>
    </body>

</html>

<script>
    const image = document.getElementById('image');
        let positionY = -100;
        const speed = 2;

        function update() {
            positionY += speed;
            image.style.top = positionY + 'px';
            if (positionY < document.documentElement.clientHeight) {
                window.requestAnimationFrame(update);
            }
        }

        window.requestAnimationFrame(update);

</script>